version: '3.8' # if no version is specificed then v1 is assumed. Recommend v2 minimum

services:
  centos-c:
    hostname: centos-c
    container_name: centos-c
    image: sahanebhushan7/ansible:ansile
    ports: 
     - ${CENTOSC_PORT_SSHD}:22
     - ${CENTOSC_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos-c/bsahane:/home/bsahane
     - ${ANSIBLE_HOME}/centos-c/root:/root
    networks:
     - diveinto.io

  centos1:
    hostname: centos1
    container_name: centos1
    image: sahanebhushan7/ansible:centos
    ports: 
     - ${CENTOS1_PORT_SSHD}:22
     - ${CENTOS1_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos1/bsahane:/home/bsahane
     - ${ANSIBLE_HOME}/centos1/root:/root
    networks:
     - diveinto.io

  centos2:
    hostname: centos2
    container_name: centos2
    image: sahanebhushan7/ansible:centos
    ports: 
     - ${CENTOS2_PORT_SSHD}:22
     - ${CENTOS2_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos2/bsahane:/home/bsahane
     - ${ANSIBLE_HOME}/centos2/root:/root
    networks:
     - diveinto.io

  centos3:
    hostname: centos3
    container_name: centos3
    image: sahanebhushan7/ansible:centos
    ports: 
     - ${CENTOS3_PORT_SSHD}:22
     - ${CENTOS3_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos3/bsahane:/home/bsahane
     - ${ANSIBLE_HOME}/centos3/root:/root
    networks:
     - diveinto.io

  centos4:
    hostname: centos4
    container_name: centos4
    image: sahanebhushan7/ansible:centos
    #image: spurin/diveintoansible:centos-sshd-2222
    ports: 
     - ${CENTOS4_PORT_SSHD}:22
     #- ${CENTOS1_PORT_SSHD}:2222
     - ${CENTOS4_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos4/bsahane:/home/bsahane
     - ${ANSIBLE_HOME}/centos4/root:/root
    networks:
     - diveinto.io

  centos5:
    hostname: centos5
    container_name: centos5
    image: sahanebhushan7/ansible:centos
    ports: 
     - ${CENTOS5_PORT_SSHD}:22
     - ${CENTOS5_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos5/bsahane:/home/bsahane
     - ${ANSIBLE_HOME}/centos5/root:/root
    networks:
     - diveinto.io

  centos6:
    hostname: centos6
    container_name: centos6
    image: sahanebhushan7/ansible:centos
    ports: 
     - ${CENTOS6_PORT_SSHD}:22
     - ${CENTOS6_PORT_TTYD}:7681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/centos6/bsahane:/home/bsahane
     - ${ANSIBLE_HOME}/centos6/root:/root
    networks:
     - diveinto.io

  # Docker in Docker
  #
  # Usage: on host that wishes to use docker
  #
  # sudo apt-get update
  # sudo apt -y install docker.io
  # export DOCKER_HOST=tcp://docker:2375
  # docker ps -a
  #
  docker:
    hostname: docker
    container_name: docker
    image: sahanebhushan7/ansible:dind
    privileged: yes
    volumes:
     - ${ANSIBLE_HOME}/shared:/shared
    networks:
     - diveinto.io

  portal:
    hostname: portal
    container_name: portal
    image: sahanebhushan7/ansible:portal
    environment:
     - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
     - centos4
     - centos5
     - centos6
     - centos1
     - centos2
     - centos3
    ports:
     - "1000:80"
    networks:
     - diveinto.io

networks:
  diveinto.io:
    name: diveinto.io
